version: '2'

services:
  db:
    image: mdillon/postgis:9.5
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "54320:5432"

  app:
    image: skygeario/skygear-server:v0.19.1
    ports:
    - "3001:3000"
    volumes:
    - app_data:/go/src/app/data
    depends_on:
    - db
    command: skygear-server
    environment:
      DATABASE_URL: postgresql://postgres:@db/postgres?sslmode=disable
      API_KEY: changeme
      MASTER_KEY: secret
      APP_NAME: _
      TOKEN_STORE: jwt
      TOKEN_STORE_SECRET: jwt_secret
      PLUGINS: PY,JS
      PY_TRANSPORT: http
      PY_PATH: http://py:8000
      JS_TRANSPORT: http
      JS_PATH: http://js:9000
      APNS_ENABLE: "YES"
      APNS_ENV: sandbox
      APNS_CERTIFICATE: #TO BE FILL IN
      APNS_PRIVATE_KEY: #TO BE FILL IN

  js:
    image: skygeario/skygear-node:canary
    command: skygear-node
    volumes:
    - .:/usr/src/app
    environment:
      NODE_PATH: /usr/local/lib/node_modules
      DATABASE_URL: postgres://postgres@db/postgres?sslmode=disable
      API_KEY: changeme
      MASTER_KEY: secret
      APP_NAME: _
      PUBSUB_URL: ws://app:3000/pubsub
      SKYGEAR_ENDPOINT: http://app:3000
      HTTP: "true"

  py:
    image: skygeario/py-skygear:v0.19.0
    command: py-skygear --http
    volumes:
    - .:/usr/src/app
    environment:
      DATABASE_URL: postgres://postgres@db/postgres?sslmode=disable
      API_KEY: changeme
      MASTER_KEY: secret
      APP_NAME: _
      PUBSUB_URL: ws://app:3000/pubsub
      SKYGEAR_ENDPOINT: http://app:3000
      HTTP: "true"

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
